<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Functions (Need)</span></div>

## 1 User defined functions

### 1.1 Named functions that return

In [2]:
def greeting(name):
    if name == 'Batman':
        return 'Hello Batman! So, nice to meet you!'
    else:
        return f'Hello {name}!'
print(greeting("Super Man"))
print(greeting(name="Super Man"))

Hello Super Man!
Hello Super Man!


In [3]:
greet=greeting(name='Super Man')
print(greet)
print(greeting(name='Super Man'))

Hello Super Man!
Hello Super Man!


In [7]:
def basic_stats(numbers):
    np_numbers=np.array(numbers)
    return np_numbers.min(), np_numbers.max(), np_numbers.mean()
list_min, list_max, list_mean = basic_stats([1, 2, 3, 4, 5])
print(list_min)
print(list_max)
print(list_mean)

1
5
3.0


### 1.2 Named functions that don’t return

### 1.3 Anonymous functions

In [8]:
my_short_function = lambda name: f"Hello {name}!"
my_short_function(name="Super Man")

'Hello Super Man!'

In [9]:
numbers=[[9, 0, 10],
         [8, 1, 11],
         [7, 2, 12],
         [6, 3, 13],
         [5, 4, 14],
         [4, 5, 15],
         [3, 6, 16],
         [2, 7, 17],
         [1, 8, 18],
         [0, 9, 19]]

sorted(numbers)                         # Sort by comparing the default key 
                                        # (i.e. the 1st element) 

[[0, 9, 19],
 [1, 8, 18],
 [2, 7, 17],
 [3, 6, 16],
 [4, 5, 15],
 [5, 4, 14],
 [6, 3, 13],
 [7, 2, 12],
 [8, 1, 11],
 [9, 0, 10]]

In [10]:
sorted(numbers, key=lambda x: x[1])     # Sort by comparing a custom key
                                        # that uses the 2nd element

[[9, 0, 10],
 [8, 1, 11],
 [7, 2, 12],
 [6, 3, 13],
 [5, 4, 14],
 [4, 5, 15],
 [3, 6, 16],
 [2, 7, 17],
 [1, 8, 18],
 [0, 9, 19]]

In [11]:
sorted(numbers, key=lambda x: sum(x))   # Sort by comparing a custom key
                                        # that uses the sum of the elements

[[9, 0, 10],
 [8, 1, 11],
 [7, 2, 12],
 [6, 3, 13],
 [5, 4, 14],
 [4, 5, 15],
 [3, 6, 16],
 [2, 7, 17],
 [1, 8, 18],
 [0, 9, 19]]

### 1.4 Optional arguments

In [12]:
def greeting(name='no one'):
    if name == 'Batman':
        return 'Hello Batman! So, nice to meet you!'
    else:
        return f'Hello {name}!'
print(greeting())

Hello no one!


In [13]:
?print

In [14]:
print('I', 'am', 'Batman!')                 # Just for comparison
#> I am Batman!
print('I', 'am', 'Batman!', sep='---')  
#> I---am---Batman!

I am Batman!
I---am---Batman!


## 2 The importance of functions?

### 2.1 An argument for functions

In [ ]:

# Your code here


### 2.2 A word of caution

In [ ]:

# Your code here


## Exercise 1 :  Do you know why?

If the name is not batman, the code will not run through the if loop, instead it will skip the if loop and run the next line of code, which is 'return f'Hello {name}!'

## Exercise 2 :  Calculator functions

In [2]:
def add(x, y):
    return x + y
print(add(3, 4))

7


In [3]:
def subtract(x, y):
    return x - y
print(subtract(1, 9))

-8


In [4]:
def multiply(x, y):
    return x * y
print(multiply(7, 9))

63


In [44]:
def divide(x, y):
    if type(y) == np.ndarray:
        if 0 in y:
            return None
        else:
            return x / y
    elif y == 0:
        return None
    else:
        return x / y
print(divide(3, 0))
print(divide(4, 3))

None
1.3333333333333333


In [46]:
import numpy as np
x=np.array([36, 34, 44, 76, 27])
y=np.array([64, 66, 56, 24, 73])
print(add(x, y))
print(subtract(x, y))
print(multiply(x, y))
print(divide(x, y))

[100 100 100 100 100]
[-28 -32 -12  52 -46]
[2304 2244 2464 1824 1971]
[0.5625     0.51515152 0.78571429 3.16666667 0.36986301]


In [45]:
x=np.array([36, 34, 44, 76, 27])
y=np.array([64, 66, 56, 0, 73])
print(divide(x, y))

None


## Exercise 3 :  max_info() with NumPy

In [16]:
def max_info(numbers):
    lst = np.array(numbers)
    return lst.max(), lst.argmax() 
print(max_info([40, 27, 83, 44, 74, 51, 76, 77, 10, 49]))

(83, 2)
