<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

## 1 Subsetting: Indexing and Slicing

### 1.1 Indexing & Slicing 1D (Lists & Arrays)

In [2]:
py_list=["a1", "b2", "c3", "d4", "e5",
         "f6", "g7", "h8", "i9", "j10"]
np_array=np.array(py_list)

x = py_list 
print(x[1:4:2])

['b2', 'd4']


### 1.2 Subsetting by masking (Arrays only)

In [4]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
my_mask = np_array > 3
print(my_mask)

[False False False  True  True  True  True  True  True  True]


In [5]:
py_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
mask = py_list > 3
print(mask)

TypeError: '>' not supported between instances of 'list' and 'int'

In [6]:
np_array[my_mask]

array([ 4,  5,  6,  7,  8,  9, 10])

In [7]:
np_array[np_array > 3]

array([ 4,  5,  6,  7,  8,  9, 10])

In [9]:
print(np_array[~(np_array > 3)])                         # '~' means 'NOT'
print(np_array[(np_array > 3) & (np_array < 8)])         # '&' means 'AND'
print(np_array[(np_array < 3) | (np_array > 8)])         # '|' means 'OR'


[1 2 3]
[4 5 6 7]
[ 1  2  9 10]


### 1.3 Indexing & Slicing 2D Lists

In [11]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]
print(py_list_2d[3])        # What is at position 4 (index 3)?

[4, 'D']


In [12]:
print(py_list_2d[3][0])     # FIRST element at position 4 (index 3)

4


In [13]:
print(py_list_2d[:3])

[[1, 'A'], [2, 'B'], [3, 'C']]


In [14]:
print(py_list_2d[:3][0])

[1, 'A']


In [15]:
py_list_2d[3:6][0]

[4, 'D']

### 1.4 Indexing & Slicing 2D Arrays

In [17]:
np_array_2d = np.array([[1, "A"], [2, "B"], [3, "C"], [4, "D"],
                        [5, "E"], [6, "F"], [7, "G"], [8, "H"],
                        [9, "I"], [10, "J"]])
print(np_array_2d[3])       # What is at position 4 (index 3)?
print(np_array_2d[3, 0])    # FIRST element at position 4 (index 3)
print(np_array_2d[:3])

['4' 'D']
4
[['1' 'A']
 ['2' 'B']
 ['3' 'C']]


In [18]:
print(np_array_2d[:3, 0])
print(np_array_2d[3:6, 0])
print(np_array_2d[:, 0])

['1' '2' '3']
['4' '5' '6']
['1' '2' '3' '4' '5' '6' '7' '8' '9' '10']


### 1.5 Growing lists

In [19]:
x = [1] * 10
print(x)

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]


In [20]:
x = [1]
x = x + [2]
x = x + [3]
x = x + [4]
print(x)

[1, 2, 3, 4]


In [21]:
x = [1]
x += [2]
x += [3]
x += [4]
print(x)

[1, 2, 3, 4]


In [23]:
x = [1]
x +=  [2, 3, 4]
print(x)

[1, 2, 3, 4]


In [24]:
x = [1]
x = [2, 3, 4] + x
print(x)

[2, 3, 4, 1]


In [25]:
x=[1]
x.append(2)
x.append(3)
x.append(4)
print(x)

[1, 2, 3, 4]


## 2 Some loose ends

### 2.1 Tuples

In [26]:
a = (1, 2, 3)     # Define tuple
print(a[0])    # Access data

1


In [27]:
# The following will NOT work
a[0] = -1
a[0] += [10]

TypeError: 'tuple' object does not support item assignment

### 2.2 Be VERY careful when copying

In [ ]:
x=[1, 2, 3]
y=x.copy()
z=x.copy()

## Exercise 1 :  Total recall?

| **Term**   | **Brief description**                        |
|:------------|:----------------------------------------------|
| Subsetting | select a subset of data from a list/array    |
| Indexing   | select an element from a list/array          |
| Slicing    | select a range of element                    |
| Masking    | only allow elements that are True to be seen |

## Exercise 2 :  Show me the ‘odd’ letters

In [42]:
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])
first_elements = np_array_2d[:, 0]
first_elements = first_elements.astype('i')
remainder = first_elements % 2 == 1
second_elements = np_array_2d[:, 1]
print(second_elements[remainder])

['A' 'C' 'E' 'G' 'I']
