<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

## 1 Lists, Arrays & Dictionaries

In [1]:
import numpy as np

### 1.1 Let’s compare

In [ ]:
# lists
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

# Array: Python does not have built-in support for Arrays, hence we need to import a the NumPy library
np_super_names = np.array(["Black Widow", "Iron Man", "Doctor Strange"])
np_real_names = np.array(["Natasha Romanoff", "Tony Stark", "Stephen Strange"])

# Dictionary
superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"
                  }

### 1.2 Accessing data from a list (or array)

In [2]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]
print(py_real_names[0])
print(py_super_names[0])
print(py_super_names[2])    # Forward indexing 
                            # We need to know the size 
                            # beforehand for this to work.
print(py_super_names[-1])   # Reverse indexing

Natasha Romanoff
Black Widow
Doctor Strange
Doctor Strange


### 1.3 Accessing data from a dictionary

In [3]:
superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"
                  }
print(superhero_info["Natasha Romanoff"])

Black Widow


In [5]:
print(superhero_info.values())

dict_values(['Black Widow', 'Iron Man', 'Doctor Strange'])


### 1.4 Higher dimensional lists

In [6]:
py_superhero_info = [['Natasha Romanoff', 'Black Widow'],
                     ['Tony Stark', 'Iron Man'],
                     ['Stephen Strange', 'Doctor Strange']]

## 2 Lists vs. Arrays

### 2.1 Size

In [7]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)      # Reusing the Python list 
                                        # to create a NEW
                                        # NumPy array
print(len(py_list_2d))
print(len(py_list_2d))

10
10


In [8]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]
print(len(py_list_2d))

10


### 2.2 Arrays are fussy about type

In [1]:
py_list = [1, 1.5, 'A']
np.array(py_list)

array(['1', '1.5', 'A'], dtype='<U32')

### 2.3 Adding a number

In [2]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         # Reusing the Python list
                                     # to create a NEW
                                     # NumPy array
print(py_list + 10)        # Won't work!

TypeError: can only concatenate list (not "int") to list

In [3]:
print(np_array + 10)

[11 12 13 14 15]


### 2.4 Adding another list

In [4]:
py_list_1 = [1, 2, 3, 4, 5]
py_list_2 = [10, 20, 30, 40, 50]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)

print(py_list_1 + py_list_2)
print(np_array_1 + np_array_2)

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]
[11 22 33 44 55]


### 2.5 Multiplying by a Number

In [5]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         
print(py_list*2)
print(np_array*2)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 2  4  6  8 10]


### 2.6 Squaring

In [6]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)
print(py_list**2)                      # Won't work!  

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [8]:
print(np_array**2)  # why is the spacing between each element different?

[ 1  4  9 16 25]


### 2.7 Asking questions

In [11]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)       
py_list == 3     # Works, but what IS the question? Is py_list equals to 3?

False

In [13]:
print(np_array == 3)
print(np_array > 3)

[False False  True False False]
[False False False  True  True]


### 2.8 Mathematics

In [14]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         
print(sum(py_list))    # sum() is a base Python function
print(max(py_list))    # max() is a base Python function
print(min(py_list))    # min() is a base Python function
py_list.sum()   # Won't work!

15
5
1


AttributeError: 'list' object has no attribute 'sum'

In [15]:
print(np_array.sum())
print(np_array.mean())
print(np_array.min())

15
3.0
1


## Exercise 1 :  Total recall?

1. Two similarities between lists and arrays.
    - both lists and arrays can be used to store values
    - len(variable_name) can be used to find the number of elements in the list/array
2. Two differences between lists and arrays.
    - lists can store a mix of data type while arrays will ensure that all the elements in it are of the same type.
    - operations work differently on lists and arrays. For instance, multiplying a list by 3 will increease the number of elements by 3 times while in an array, each element will be multiplied.    
3. What is a dictionary?
    - dictionary helps to store elements paired with a key.

## Exercise 2 :  Index me

In [8]:
py_list = ["a1", "b2", "c3", "d4", "e5", "f6", "g7", "h8", "i9", "j10"]

for i in range(len(py_list) - 1):
    if int(py_list[i][1]) % 2 == 1:
        print(py_list[i])

a1
c3
e5
g7
i9


In [9]:
py_list = ["a1", "b2", "c3", "d4", "e5", "f6", "g7", "h8", "i9", "j10"]
print(py_list[0])   # Prints 'a1'
print(py_list[2])   # Prints 'c3'
print(py_list[4])   # Prints 'e5'
print(py_list[6])   # Prints 'g7'
print(py_list[8])   # Prints 'i9'

a1
c3
e5
g7
i9


## Exercise 3 :  Capitalise Heros

In [11]:
superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"
                  }

superhero_info['Tony Stark'] = superhero_info['Tony Stark'].upper() 
superhero_info['Natasha Romanoff'] = superhero_info['Natasha Romanoff'].upper()
superhero_info['Stephen Strange'] = superhero_info['Stephen Strange'].upper()
print(superhero_info.values())

dict_values(['BLACK WIDOW', 'IRON MAN', 'DOCTOR STRANGE'])


## Exercise 4 :  How many ones

In [16]:
numbers = [45, 60, 1, 30, 96, 1, 96, 57, 16, 1, 99, 62, 86, 43, 42, 60, 59, 1, 1, 35, 83, 47, 34, 28, 68, 23, 22, 92, 1, 79, 1, 29, 94, 72, 46, 47, 1, 74, 32, 20, 8, 37, 35, 1, 89, 29, 86, 19, 43, 61]      

numbers = np.array(numbers)
equals_one = (numbers == 1)
print(sum(equals_one))


9
